In [ ]:
with open("/content/CBOW.txt","r") as file:
  contents = file.read()
contents

'The speed of transmission is an important point of difference between the two viruses. Influenza has a shorter median incubation period (the time from infection to appearance of symptoms) and a shorter serial interval (the time between successive cases) than COVID-19 virus. The serial interval for COVID-19 virus is estimated to be 5-6 days, while for influenza virus, the serial interval is 3 days. This means that influenza can spread faster than COVID-19. \n\nFurther, transmission in the first 3-5 days of illness, or potentially pre-symptomatic transmission –transmission of the virus before the appearance of symptoms – is a major driver of transmission for influenza. In contrast, while we are learning that there are people who can shed COVID-19 virus 24-48 hours prior to symptom onset, at present, this does not appear to be a major driver of transmission. \n\nThe reproductive number – the number of secondary infections generated from one infected individual – is understood to be betwe

In [ ]:
sentences = contents.split(".")
sentences

['The speed of transmission is an important point of difference between the two viruses',
 ' Influenza has a shorter median incubation period (the time from infection to appearance of symptoms) and a shorter serial interval (the time between successive cases) than COVID-19 virus',
 ' The serial interval for COVID-19 virus is estimated to be 5-6 days, while for influenza virus, the serial interval is 3 days',
 ' This means that influenza can spread faster than COVID-19',
 ' \n\nFurther, transmission in the first 3-5 days of illness, or potentially pre-symptomatic transmission –transmission of the virus before the appearance of symptoms – is a major driver of transmission for influenza',
 ' In contrast, while we are learning that there are people who can shed COVID-19 virus 24-48 hours prior to symptom onset, at present, this does not appear to be a major driver of transmission',
 ' \n\nThe reproductive number – the number of secondary infections generated from one infected individual – 

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
tokenizer.word_index

{'the': 1,
 'of': 2,
 'influenza': 3,
 'covid': 4,
 '19': 5,
 'virus': 6,
 'for': 7,
 'transmission': 8,
 'is': 9,
 'to': 10,
 'a': 11,
 'and': 12,
 'between': 13,
 'time': 14,
 'serial': 15,
 'interval': 16,
 'than': 17,
 'be': 18,
 '5': 19,
 'days': 20,
 '–': 21,
 'are': 22,
 'viruses': 23,
 'shorter': 24,
 'from': 25,
 'appearance': 26,
 'symptoms': 27,
 'while': 28,
 '3': 29,
 'this': 30,
 'that': 31,
 'can': 32,
 'in': 33,
 'major': 34,
 'driver': 35,
 'number': 36,
 '2': 37,
 'speed': 38,
 'an': 39,
 'important': 40,
 'point': 41,
 'difference': 42,
 'two': 43,
 'has': 44,
 'median': 45,
 'incubation': 46,
 'period': 47,
 'infection': 48,
 'successive': 49,
 'cases': 50,
 'estimated': 51,
 '6': 52,
 'means': 53,
 'spread': 54,
 'faster': 55,
 'further': 56,
 'first': 57,
 'illness': 58,
 'or': 59,
 'potentially': 60,
 'pre': 61,
 'symptomatic': 62,
 '–transmission': 63,
 'before': 64,
 'contrast': 65,
 'we': 66,
 'learning': 67,
 'there': 68,
 'people': 69,
 'who': 70,
 'shed': 7

In [ ]:
ts = tokenizer.texts_to_sequences(sentences)
ts

[[1, 38, 2, 8, 9, 39, 40, 41, 2, 42, 13, 1, 43, 23],
 [3,
  44,
  11,
  24,
  45,
  46,
  47,
  1,
  14,
  25,
  48,
  10,
  26,
  2,
  27,
  12,
  11,
  24,
  15,
  16,
  1,
  14,
  13,
  49,
  50,
  17,
  4,
  5,
  6],
 [1,
  15,
  16,
  7,
  4,
  5,
  6,
  9,
  51,
  10,
  18,
  19,
  52,
  20,
  28,
  7,
  3,
  6,
  1,
  15,
  16,
  9,
  29,
  20],
 [30, 53, 31, 3, 32, 54, 55, 17, 4, 5],
 [56,
  8,
  33,
  1,
  57,
  29,
  19,
  20,
  2,
  58,
  59,
  60,
  61,
  62,
  8,
  63,
  2,
  1,
  6,
  64,
  1,
  26,
  2,
  27,
  21,
  9,
  11,
  34,
  35,
  2,
  8,
  7,
  3],
 [33,
  65,
  28,
  66,
  22,
  67,
  31,
  68,
  22,
  69,
  70,
  32,
  71,
  4,
  5,
  6,
  72,
  73,
  74,
  75,
  10,
  76,
  77,
  78,
  79,
  30,
  80,
  81,
  82,
  10,
  18,
  11,
  34,
  35,
  2,
  8],
 [1,
  83,
  36,
  21,
  1,
  36,
  2,
  84,
  85,
  86,
  25,
  87,
  88,
  89,
  21,
  9,
  90,
  10,
  18,
  13,
  37,
  12,
  37],
 [19, 7, 4, 5, 6, 91, 17, 7, 3],
 [92,
  93,
  7,
  94,
  4,
  5,
  12,
 

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
ws = 2
data = []
label = []

for s in ts:
  for i,w in enumerate(s):
    context = [
        s[j] for j in range(max(0,i-ws),min(i+ws+1,len(s))) if i!=j
    ]
    data.append(context)
    label.append(w)
data = pad_sequences(data)
label = np.array(label)

In [ ]:
data

array([[  0,   0,  38,   2],
       [  0,   1,   2,   8],
       [  1,  38,   8,   9],
       [ 38,   2,   9,  39],
       [  2,   8,  39,  40],
       [  8,   9,  40,  41],
       [  9,  39,  41,   2],
       [ 39,  40,   2,  42],
       [ 40,  41,  42,  13],
       [ 41,   2,  13,   1],
       [  2,  42,   1,  43],
       [ 42,  13,  43,  23],
       [  0,  13,   1,  23],
       [  0,   0,   1,  43],
       [  0,   0,  44,  11],
       [  0,   3,  11,  24],
       [  3,  44,  24,  45],
       [ 44,  11,  45,  46],
       [ 11,  24,  46,  47],
       [ 24,  45,  47,   1],
       [ 45,  46,   1,  14],
       [ 46,  47,  14,  25],
       [ 47,   1,  25,  48],
       [  1,  14,  48,  10],
       [ 14,  25,  10,  26],
       [ 25,  48,  26,   2],
       [ 48,  10,   2,  27],
       [ 10,  26,  27,  12],
       [ 26,   2,  12,  11],
       [  2,  27,  11,  24],
       [ 27,  12,  24,  15],
       [ 12,  11,  15,  16],
       [ 11,  24,  16,   1],
       [ 24,  15,   1,  14],
       [ 15,  

In [ ]:
label

array([  1,  38,   2,   8,   9,  39,  40,  41,   2,  42,  13,   1,  43,
        23,   3,  44,  11,  24,  45,  46,  47,   1,  14,  25,  48,  10,
        26,   2,  27,  12,  11,  24,  15,  16,   1,  14,  13,  49,  50,
        17,   4,   5,   6,   1,  15,  16,   7,   4,   5,   6,   9,  51,
        10,  18,  19,  52,  20,  28,   7,   3,   6,   1,  15,  16,   9,
        29,  20,  30,  53,  31,   3,  32,  54,  55,  17,   4,   5,  56,
         8,  33,   1,  57,  29,  19,  20,   2,  58,  59,  60,  61,  62,
         8,  63,   2,   1,   6,  64,   1,  26,   2,  27,  21,   9,  11,
        34,  35,   2,   8,   7,   3,  33,  65,  28,  66,  22,  67,  31,
        68,  22,  69,  70,  32,  71,   4,   5,   6,  72,  73,  74,  75,
        10,  76,  77,  78,  79,  30,  80,  81,  82,  10,  18,  11,  34,
        35,   2,   8,   1,  83,  36,  21,   1,  36,   2,  84,  85,  86,
        25,  87,  88,  89,  21,   9,  90,  10,  18,  13,  37,  12,  37,
        19,   7,   4,   5,   6,  91,  17,   7,   3,  92,  93,   

In [ ]:
tw = len(tokenizer.word_index)+1

In [ ]:
from tensorflow.keras.layers import Dense, GlobalAveragePooling1D, Embedding
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Embedding(input_dim = tw,output_dim = 50,input_length = ws*2))
model.add(GlobalAveragePooling1D())
model.add(Dense(tw,activation="softmax"))

model.compile(loss="sparse_categorical_crossentropy",optimizer = "adam",metrics = ["accuracy"])
model.summary()
model.fit(data,label,epochs=200)

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 4, 50)             5150      
                                                                 
 global_average_pooling1d_5  (None, 50)                0         
  (GlobalAveragePooling1D)                                       
                                                                 
 dense_5 (Dense)             (None, 103)               5253      
                                                                 
Total params: 10403 (40.64 KB)
Trainable params: 10403 (40.64 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/200
7/7 [==============================] - 1s 4ms/step - loss: 4.6349 - accuracy: 0.0202
Epoch 2/200
7/7 [==============================] - 0s 3ms/step - loss: 4.6239 - accuracy: 0.0859
Epoch 3/200
7/7 [=====

In [ ]:
we = model.layers[0].get_weights()[0]
we

array([[-0.41992092, -0.05589909,  0.5096379 , ...,  0.73421085,
        -0.00166634, -0.9476329 ],
       [-0.6245062 , -0.78741205, -0.20820232, ..., -0.27558115,
         0.31825608, -0.27899477],
       [-0.16218661, -0.7094083 ,  0.059572  , ..., -0.8094629 ,
         0.19691083, -0.5900967 ],
       ...,
       [ 0.48341286,  0.64101374, -0.645196  , ...,  0.52279556,
        -0.5261266 ,  0.49211505],
       [ 0.09363004,  0.36077327, -0.38420767, ...,  0.37354916,
        -0.70083565,  0.36611488],
       [ 0.51502067, -0.7037997 , -0.3976244 , ...,  0.3769721 ,
         0.0785154 , -0.5274245 ]], dtype=float32)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
t = "influenza"
te = we[tokenizer.word_index[t]]
te

array([ 0.51055145,  0.5363594 ,  0.77793837,  0.7550279 , -0.7810462 ,
       -0.42021388,  0.20618746, -0.43508404,  1.018991  , -0.6416889 ,
        0.42367864,  0.6644842 , -0.4887644 , -1.0334806 , -0.66784424,
       -0.19320308, -0.41193822,  0.33857307,  0.1153147 ,  0.2787886 ,
        0.79047495, -0.00204601, -0.9319941 ,  0.05632305, -0.3738318 ,
       -0.6810332 ,  0.43767944, -0.17054474, -0.5998863 ,  0.49215874,
        0.1188921 , -0.29447794, -0.26052547,  0.44965026,  0.15753657,
        0.9830336 , -0.8792677 , -0.7970589 , -0.0601784 ,  0.29297468,
       -0.00196408, -0.14013508,  0.3277034 ,  0.10523552,  0.6990555 ,
       -0.2629907 , -0.02479551,  0.09281021, -0.37646362, -0.51882875],
      dtype=float32)

In [ ]:
sim = cosine_similarity(te.reshape(1,-1),we)[0]
sim

array([ 0.23296526, -0.22640039,  0.04314022,  1.        ,  0.52954113,
        0.20279826,  0.02986952, -0.06076547, -0.04893762, -0.14554244,
       -0.27178702, -0.2224316 , -0.12293055, -0.07795855, -0.06081665,
        0.3033291 , -0.07016285,  0.03220641, -0.20682281, -0.16750278,
        0.0802068 , -0.12243782,  0.1549968 ,  0.10962274,  0.429944  ,
       -0.21072687, -0.37860578,  0.0410655 ,  0.28041065, -0.18392828,
        0.07497036,  0.26945466,  0.00863528,  0.10709475,  0.07111205,
        0.16805898, -0.04857558,  0.07870336,  0.14049943,  0.20627262,
       -0.13757932, -0.03448765, -0.11672293,  0.15585549,  0.20832308,
        0.08744998, -0.0059222 ,  0.0946316 , -0.33546293,  0.01222519,
       -0.1640033 , -0.10134105,  0.03850247,  0.23027045,  0.28265926,
        0.3126504 ,  0.36461505,  0.10413657, -0.14916004, -0.13592082,
       -0.01636845,  0.05223527,  0.05931459,  0.09737225,  0.2137115 ,
        0.2570875 ,  0.1897823 ,  0.2200255 ,  0.19667742,  0.12

In [ ]:
msim = sim.argsort()[-5:][::-1]
msim

array([ 3, 91,  4, 92, 95])

In [ ]:
tokenizer.word_index.items()

dict_items([('the', 1), ('of', 2), ('influenza', 3), ('covid', 4), ('19', 5), ('virus', 6), ('for', 7), ('transmission', 8), ('is', 9), ('to', 10), ('a', 11), ('and', 12), ('between', 13), ('time', 14), ('serial', 15), ('interval', 16), ('than', 17), ('be', 18), ('5', 19), ('days', 20), ('–', 21), ('are', 22), ('viruses', 23), ('shorter', 24), ('from', 25), ('appearance', 26), ('symptoms', 27), ('while', 28), ('3', 29), ('this', 30), ('that', 31), ('can', 32), ('in', 33), ('major', 34), ('driver', 35), ('number', 36), ('2', 37), ('speed', 38), ('an', 39), ('important', 40), ('point', 41), ('difference', 42), ('two', 43), ('has', 44), ('median', 45), ('incubation', 46), ('period', 47), ('infection', 48), ('successive', 49), ('cases', 50), ('estimated', 51), ('6', 52), ('means', 53), ('spread', 54), ('faster', 55), ('further', 56), ('first', 57), ('illness', 58), ('or', 59), ('potentially', 60), ('pre', 61), ('symptomatic', 62), ('–transmission', 63), ('before', 64), ('contrast', 65), ('

In [ ]:
msimw = [word for word,i in tokenizer.word_index.items() if i in msim]
msimw

['influenza', 'covid', 'higher', 'however', 'very']